# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI with sbt and Coveralls
# Trigger auf Push und Pull Requests für alle Branches
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest # Wählen Sie das Betriebssystem aus, das Sie verwenden möchten
    steps:
    # Schritt 1: Checkout des Repositories
    - name: Checkout code
      uses: actions/checkout@v3
    # Schritt 2: Installieren von Java (JDK 11+ wird oft für sbt empfohlen)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # Schritt 3: Installieren von sbt (build tool für Scala)
    - name: Install sbt
      uses: olafurpg/setup-scala@v10
      with:
        scala-version: '1.10.3' # Passen Sie die Scala-Version an Ihre Bedürfnisse an
        sbt-version: '1.10.3'     # Geben Sie die passende sbt-Version an
    # Schritt 4: Abhängigkeiten auflösen und Projekt bauen
    - name: sbt compile
      run: sbt compile

    # Schritt 5: Tests ausführen
    - name: sbt clean coverage test
      run: sbt clean coverage test

    # Schritt 6: Coverage generiere
    - name: sbt coverageReport
